version: '3.9'
services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /livekit.yaml
    restart: always
    ports:
      # Порт для управления (HTTP/WebSocket)
      - "7880:7880"
      # Порты для передачи видео и аудио (WebRTC)
      - "50000-50050:50000-50050/udp"
    volumes:
      # Пробрасываем файл настроек внутрь контейнера
      - ./livekit.yaml:/livekit.yaml
